# Generated by Django 5.0.6 on 2026-08-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'core_sequence',
            },
        ),
    ]
