# Generated by Django 5.0.6 on 2026-08-02 09:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Jina la Mfuko')),
                ('name_en', models.CharField(blank=True, max_length=80)),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('is_restricted', models.BooleanField(default=False, verbose_name='Fedha zenye masharti')),
                ('colour', models.CharField(default='#12864a', max_length=20)),
                ('icon', models.CharField(default='coins', max_length=30)),
                ('annual_target', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Lengo la mwaka')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Mfuko',
                'verbose_name_plural': 'Mifuko',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('savings', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Akiba')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='members.member')),
            ],
            options={
                'verbose_name': 'Akaunti ya Mwanachama',
                'verbose_name_plural': 'Akaunti za Wanachama',
            },
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, verbose_name='Jina')),
                ('donor_type', models.CharField(choices=[('individual', 'Mtu binafsi'), ('company', 'Kampuni'), ('organisation', 'Shirika'), ('member', 'Mwanachama')], default='individual', max_length=16)),
                ('country', models.CharField(blank=True, default='Tanzania', max_length=60)),
                ('phone', models.CharField(blank=True, max_length=24)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_partner', models.BooleanField(default=False, verbose_name='Ni mdau')),
                ('is_active', models.BooleanField(default=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donor_profiles', to='members.member')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.region')),
            ],
            options={
                'verbose_name': 'Mhisani / Mdau',
                'verbose_name_plural': 'Wahisani na Wadau',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160, verbose_name='Kampeni')),
                ('title_en', models.CharField(blank=True, max_length=160)),
                ('summary', models.TextField(blank=True)),
                ('summary_en', models.TextField(blank=True)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Lengo')),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField()),
                ('scene', models.CharField(default='sadaka', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('fund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='finance.fund')),
            ],
            options={
                'verbose_name': 'Kampeni',
                'verbose_name_plural': 'Kampeni',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Chanya = ingizo, hasi = toleo', max_digits=14)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('entry_date', models.DateField(default=django.utils.timezone.localdate)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='finance.account')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='finance.fund')),
                ('reverses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_by', to='finance.ledgerentry')),
            ],
            options={
                'verbose_name': 'Ingizo la Leja',
                'verbose_name_plural': 'Leja',
                'ordering': ['-entry_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160, verbose_name='Mradi')),
                ('title_en', models.CharField(blank=True, max_length=160)),
                ('summary', models.TextField(blank=True, verbose_name='Maelezo')),
                ('summary_en', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('completed', 'Imekamilika'), ('ongoing', 'Inaendelea'), ('paused', 'Imesimama'), ('planned', 'Haijaanza')], default='ongoing', max_length=12)),
                ('target_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Lengo')),
                ('scene', models.CharField(default='ujenzi', help_text='Mchoro: msikiti, elimu, afya, maji, ujenzi...', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.region')),
            ],
            options={
                'verbose_name': 'Mradi',
                'verbose_name_plural': 'Miradi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Maelezo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('spent_on', models.DateField(default=django.utils.timezone.localdate)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.fund')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.project')),
            ],
            options={
                'verbose_name': 'Matumizi',
                'verbose_name_plural': 'Matumizi',
                'ordering': ['-spent_on'],
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_no', models.CharField(blank=True, max_length=32, unique=True)),
                ('donor_name', models.CharField(blank=True, max_length=160, verbose_name='Jina la Mchangiaji')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Kiasi')),
                ('method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('airtel', 'Airtel Money'), ('tigo', 'Tigo Pesa'), ('halo', 'HaloPesa'), ('mixx', 'Mixx by Yas'), ('bank', 'Benki'), ('cash', 'Taslimu'), ('card', 'Kadi ya Benki')], default='mpesa', max_length=12)),
                ('bank_name', models.CharField(blank=True, max_length=60)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=120)),
                ('status', models.CharField(choices=[('confirmed', 'Yaliyothibitisha'), ('pending', 'Yanasubiri Uthibitisho'), ('failed', 'Yaliyokosekana'), ('cancelled', 'Yameghairiwa')], default='confirmed', max_length=12)),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Maelezo')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to='finance.campaign')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to='members.member')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions_recorded', to=settings.AUTH_USER_MODEL)),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to='finance.donor')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='finance.fund')),
                ('ledger_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribution', to='finance.ledgerentry')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to='finance.project')),
            ],
            options={
                'verbose_name': 'Mchango',
                'verbose_name_plural': 'Michango',
                'ordering': ['-received_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='finance.project'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_no', models.CharField(blank=True, max_length=32, unique=True, verbose_name='Namba ya Risiti')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Kiasi')),
                ('year', models.PositiveSmallIntegerField(default=2026, verbose_name='Mwaka')),
                ('period_month', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Mwezi')),
                ('method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('airtel', 'Airtel Money'), ('tigo', 'Tigo Pesa'), ('halo', 'HaloPesa'), ('mixx', 'Mixx by Yas'), ('bank', 'Benki'), ('cash', 'Taslimu'), ('card', 'Kadi ya Benki')], default='mpesa', max_length=12, verbose_name='Njia ya Malipo')),
                ('bank_name', models.CharField(blank=True, max_length=60)),
                ('reference', models.CharField(blank=True, max_length=80, verbose_name='Kumbukumbu')),
                ('idempotency_key', models.CharField(blank=True, db_index=True, help_text='Huzuia malipo kuingia mara mbili kutoka gateway', max_length=120)),
                ('status', models.CharField(choices=[('confirmed', 'Yaliyothibitisha'), ('pending', 'Yanasubiri Uthibitisho'), ('failed', 'Yaliyokosekana'), ('cancelled', 'Yameghairiwa')], default='confirmed', max_length=12)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tarehe ya Malipo')),
                ('ledger_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='finance.ledgerentry')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='members.member')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Malipo ya Ada',
                'verbose_name_plural': 'Malipo ya Ada',
                'ordering': ['-paid_at', '-id'],
                'indexes': [models.Index(fields=['status'], name='finance_pay_status_cb601d_idx'), models.Index(fields=['paid_at'], name='finance_pay_paid_at_ef8be0_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('idempotency_key',), name='uniq_payment_idempotency'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['fund'], name='finance_con_fund_id_d81c46_idx'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['received_at'], name='finance_con_receive_ba21ef_idx'),
        ),
    ]
