# Generated by Django 5.0.6 on 2026-08-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_donor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='currency',
            field=models.CharField(default='TZS', max_length=3, verbose_name='Fedha'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='entered_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Kiasi alichoweka'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='purpose',
            field=models.CharField(blank=True, help_text='Zakat, Sadaqah, Waqf n.k. — angalia core/data/giving.py', max_length=32, verbose_name='Aina ya mchango'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='recurrence',
            field=models.CharField(blank=True, default='once', max_length=16, verbose_name='Kurudia'),
        ),
    ]
