# Generated by Django 5.0.6 on 2026-08-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_contribution_currency_contribution_entered_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='gateway',
            field=models.CharField(blank=True, max_length=20, verbose_name='Mtoa huduma'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='gateway_ref',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Namba ya mtoa huduma'),
        ),
    ]
