# Generated by Django 5.0.6 on 2026-08-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_contribution_gateway_contribution_gateway_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='method',
            field=models.CharField(choices=[('pesapal', 'Mtandaoni (Pesapal)'), ('mpesa', 'M-Pesa'), ('airtel', 'Airtel Money'), ('tigo', 'Tigo Pesa'), ('halo', 'HaloPesa'), ('mixx', 'Mixx by Yas'), ('bank', 'Benki'), ('cash', 'Taslimu'), ('card', 'Kadi ya Benki')], default='mpesa', max_length=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('pesapal', 'Mtandaoni (Pesapal)'), ('mpesa', 'M-Pesa'), ('airtel', 'Airtel Money'), ('tigo', 'Tigo Pesa'), ('halo', 'HaloPesa'), ('mixx', 'Mixx by Yas'), ('bank', 'Benki'), ('cash', 'Taslimu'), ('card', 'Kadi ya Benki')], default='mpesa', max_length=12, verbose_name='Njia ya Malipo'),
        ),
    ]
