# Generated by Django 5.0.6 on 2026-08-14 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_contribution_method_alter_payment_method'),
        ('members', '0009_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='members.application', verbose_name='Ombi la Uanachama'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='membership_applied',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
