# Generated by Django 5.0.6 on 2026-08-19 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_mark_legacy_fees_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='months',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Miezi Iliyolipiwa'),
        ),
    ]
