# Generated by Django 5.0.6 on 2026-08-24 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_contribution_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='donor_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Simu ya Mchangiaji'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='sms_sent',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
