# Generated by Django 5.0.6 on 2026-09-24 02:07

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0009_contribution_donor_phone_contribution_sms_sent"),
        ("members", "0013_member_members_mem_status_963ff1_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        max_length=3, unique=True, verbose_name="Alama ya Fedha"
                    ),
                ),
                ("name", models.CharField(max_length=60, verbose_name="Jina")),
                (
                    "symbol",
                    models.CharField(
                        default="", max_length=8, verbose_name="Kiashiria"
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=1,
                        max_digits=14,
                        verbose_name="Shilingi kwa kipimo kimoja",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Inatumika"),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Kiwango cha Fedha",
                "verbose_name_plural": "Viwango vya Fedha",
                "ordering": ["order", "code"],
            },
        ),
        migrations.AddField(
            model_name="contribution",
            name="donor_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Barua Pepe ya Mchangiaji"
            ),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="method",
            field=models.CharField(
                choices=[
                    ("pesapal", "Mtandaoni (Pesapal)"),
                    ("selcom", "Mtandaoni (Selcom)"),
                    ("mpesa", "M-Pesa"),
                    ("airtel", "Airtel Money"),
                    ("tigo", "Tigo Pesa"),
                    ("halo", "HaloPesa"),
                    ("mixx", "Mixx by Yas"),
                    ("bank", "Benki"),
                    ("cash", "Taslimu"),
                    ("card", "Kadi ya Benki"),
                ],
                default="mpesa",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("pesapal", "Mtandaoni (Pesapal)"),
                    ("selcom", "Mtandaoni (Selcom)"),
                    ("mpesa", "M-Pesa"),
                    ("airtel", "Airtel Money"),
                    ("tigo", "Tigo Pesa"),
                    ("halo", "HaloPesa"),
                    ("mixx", "Mixx by Yas"),
                    ("bank", "Benki"),
                    ("cash", "Taslimu"),
                    ("card", "Kadi ya Benki"),
                ],
                default="mpesa",
                max_length=12,
                verbose_name="Njia ya Malipo",
            ),
        ),
        migrations.AddConstraint(
            model_name="contribution",
            constraint=models.UniqueConstraint(
                condition=models.Q(("gateway_ref__gt", "")),
                fields=("gateway", "gateway_ref"),
                name="uniq_contribution_gateway_ref",
            ),
        ),
    ]
