# Generated by Django 5.0.6 on 2026-08-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Msimamizi Mkuu'), ('admin', 'Msimamizi'), ('management', 'Afisa wa Usimamizi'), ('registration', 'Afisa Usajili'), ('finance', 'Afisa Malipo ya Ada'), ('contributions', 'Afisa Michango'), ('welfare', 'Afisa Ustawi'), ('outreach', 'Afisa Wadau na Wahisani'), ('coordinator', 'Mratibu wa Mkoa'), ('member', 'Mwanachama'), ('donor', 'Mhisani')], default='member', max_length=24, verbose_name='Jukumu'),
        ),
    ]
