# Generated by Django 5.0.6 on 2026-08-23 07:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('purpose', models.CharField(choices=[('phone', 'Kuthibitisha Namba ya Simu'), ('login', 'Kuingia kwenye Mfumo')], max_length=12)),
                ('code_hash', models.CharField(max_length=128)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=80)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Code ya Uthibitisho',
                'verbose_name_plural': 'Code za Uthibitisho',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone', 'purpose'], name='accounts_ve_phone_d044c4_idx')],
            },
        ),
    ]
