# Generated by Django 5.0.6 on 2026-08-02 09:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('name_en', models.CharField(blank=True, max_length=80)),
                ('icon', models.CharField(default='hand-heart', max_length=30)),
            ],
            options={
                'verbose_name': 'Aina ya Msaada',
                'verbose_name_plural': 'Aina za Msaada',
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('name_en', models.CharField(blank=True, max_length=80)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('colour', models.CharField(default='#12864a', max_length=20)),
                ('scene', models.CharField(default='tukio', max_length=20)),
            ],
            options={
                'verbose_name': 'Aina ya Tukio',
                'verbose_name_plural': 'Aina za Matukio',
            },
        ),
        migrations.CreateModel(
            name='PointRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('activity', models.CharField(max_length=140, verbose_name='Shughuli')),
                ('activity_en', models.CharField(blank=True, max_length=140)),
                ('points', models.PositiveIntegerField(default=10, verbose_name='Pointi')),
                ('note', models.CharField(blank=True, max_length=120)),
                ('note_en', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Kanuni ya Pointi',
                'verbose_name_plural': 'Kanuni za Pointi',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='Tuzo')),
                ('title_en', models.CharField(blank=True, max_length=140)),
                ('description', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('points_required', models.PositiveIntegerField(default=1000, verbose_name='Pointi zinazohitajika')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tuzo',
                'verbose_name_plural': 'Tuzo',
                'ordering': ['points_required'],
            },
        ),
        migrations.CreateModel(
            name='AssistanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=32, unique=True)),
                ('description', models.TextField(verbose_name='Maelezo')),
                ('amount_requested', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount_approved', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Inasubiri'), ('review', 'Kwenye Usahihishaji'), ('approved', 'Imeidhinishwa'), ('rejected', 'Imekataliwa'), ('paid', 'Imelipwa')], default='pending', max_length=12)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assistance_requests', to='members.member')),
                ('assistance_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programs.assistancetype')),
            ],
            options={
                'verbose_name': 'Ombi la Msaada',
                'verbose_name_plural': 'Maombi ya Msaada',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180, verbose_name='Tukio')),
                ('title_en', models.CharField(blank=True, max_length=180)),
                ('summary', models.TextField(blank=True, verbose_name='Maelezo')),
                ('summary_en', models.TextField(blank=True)),
                ('venue', models.CharField(blank=True, max_length=160, verbose_name='Ukumbi')),
                ('venue_en', models.CharField(blank=True, max_length=160)),
                ('start_at', models.DateTimeField(verbose_name='Kuanza')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='Kumalizika')),
                ('status', models.CharField(choices=[('planned', 'Imepangwa'), ('done', 'Imefanyika'), ('postponed', 'Imeahirishwa'), ('cancelled', 'Imeghairiwa')], default='planned', max_length=12)),
                ('is_public', models.BooleanField(default=True, verbose_name='Ionekane kwenye tovuti')),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='geo.region')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='programs.eventtype')),
            ],
            options={
                'verbose_name': 'Tukio',
                'verbose_name_plural': 'Matukio',
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(blank=True, max_length=140)),
                ('phone', models.CharField(blank=True, max_length=24)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('attended', models.BooleanField(default=False, verbose_name='Alihudhuria')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='programs.event')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_registrations', to='members.member')),
            ],
            options={
                'verbose_name': 'Usajili wa Tukio',
                'verbose_name_plural': 'Usajili wa Matukio',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('points', models.IntegerField(help_text='Chanya = kupata, hasi = kutumia')),
                ('reason', models.CharField(blank=True, max_length=160)),
                ('source', models.CharField(blank=True, max_length=80)),
                ('awarded_on', models.DateField(default=django.utils.timezone.localdate)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to='members.member')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.pointrule')),
            ],
            options={
                'verbose_name': 'Muamala wa Pointi',
                'verbose_name_plural': 'Miamala ya Pointi',
                'ordering': ['-awarded_on', '-id'],
            },
        ),
    ]
