# Generated by Django 5.0.6 on 2026-08-16 13:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_mark_legacy_fees_applied'),
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pointrule',
            name='kind',
            field=models.CharField(choices=[('money', 'Michango na Ada'), ('participation', 'Ushiriki'), ('bonus', 'Bonasi'), ('reversal', 'Marekebisho')], default='participation', max_length=16, verbose_name='Aina'),
        ),
        migrations.AddField(
            model_name='pointtransaction',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pointtransaction',
            name='awarded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_awarded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pointtransaction',
            name='kind',
            field=models.CharField(choices=[('money', 'Michango na Ada'), ('participation', 'Ushiriki'), ('bonus', 'Bonasi'), ('reversal', 'Marekebisho')], default='participation', max_length=16),
        ),
        migrations.AddField(
            model_name='pointtransaction',
            name='reverses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='programs.pointtransaction'),
        ),
        migrations.CreateModel(
            name='PointBoost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('multiplier', models.DecimalField(decimal_places=2, default=2, max_digits=4, verbose_name='Mara')),
                ('starts_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='Kuanzia')),
                ('ends_on', models.DateField(verbose_name='Hadi')),
                ('reason', models.CharField(max_length=160, verbose_name='Sababu')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_boosts', to='finance.fund', verbose_name='Mfuko')),
            ],
            options={
                'verbose_name': 'Bonasi ya Pointi',
                'verbose_name_plural': 'Bonasi za Pointi',
                'ordering': ['-starts_on'],
            },
        ),
    ]
