# Generated by Django 5.0.6 on 2026-09-03 00:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_leadership'),
        ('members', '0012_application_phone_verified'),
        ('programs', '0002_pointrule_kind_pointtransaction_approved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('ward', 'Kata'), ('district', 'Wilaya'), ('region', 'Mkoa'), ('zone', 'Kanda'), ('national', 'Taifa')], max_length=12, verbose_name='Ngazi')),
                ('subject', models.CharField(max_length=160, verbose_name='Kichwa')),
                ('body', models.TextField(verbose_name='Ujumbe')),
                ('reached', models.PositiveIntegerField(default=0)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to='geo.district')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to='geo.region')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to=settings.AUTH_USER_MODEL, verbose_name='Mtumaji')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to='geo.ward')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to='geo.zone')),
            ],
            options={
                'verbose_name': 'Tangazo la Kiongozi',
                'verbose_name_plural': 'Matangazo ya Viongozi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=40, unique=True, verbose_name='Namba ya Kumbukumbu')),
                ('subject', models.CharField(max_length=160, verbose_name='Kichwa')),
                ('body', models.TextField(verbose_name='Maelezo')),
                ('category', models.CharField(choices=[('welfare', 'Ustawi na Msaada'), ('finance', 'Ada na Malipo'), ('membership', 'Uanachama na Kadi'), ('complaint', 'Malalamiko'), ('suggestion', 'Ushauri na Mapendekezo'), ('other', 'Nyingine')], default='other', max_length=12, verbose_name='Aina')),
                ('urgency', models.CharField(choices=[('low', 'Si ya Haraka'), ('normal', 'Kawaida'), ('high', 'Ya Haraka')], default='normal', max_length=8, verbose_name='Uzito')),
                ('status', models.CharField(choices=[('open', 'Limefunguliwa'), ('in_progress', 'Linashughulikiwa'), ('escalated', 'Limepandishwa'), ('resolved', 'Limetatuliwa'), ('closed', 'Limefungwa')], db_index=True, default='open', max_length=12, verbose_name='Hali')),
                ('level', models.CharField(choices=[('ward', 'Kata'), ('district', 'Wilaya'), ('region', 'Mkoa'), ('zone', 'Kanda'), ('national', 'Taifa')], db_index=True, default='ward', max_length=12, verbose_name='Ngazi')),
                ('level_since', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True, verbose_name='Suluhisho')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='geo.district')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='members.member', verbose_name='Mwanachama')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='geo.region')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='geo.ward')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='geo.zone')),
            ],
            options={
                'verbose_name': 'Tatizo',
                'verbose_name_plural': 'Matatizo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('opened', 'Limefunguliwa'), ('comment', 'Maoni'), ('escalated', 'Limepandishwa na kiongozi'), ('auto_escalated', 'Limepanda lenyewe kwa muda'), ('resolved', 'Limetatuliwa'), ('closed', 'Limefungwa'), ('reopened', 'Limefunguliwa upya')], max_length=16)),
                ('note', models.TextField(blank=True)),
                ('to_level', models.CharField(blank=True, max_length=12)),
                ('internal', models.BooleanField(default=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_events', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='programs.case')),
            ],
            options={
                'verbose_name': 'Hatua ya Tatizo',
                'verbose_name_plural': 'Hatua za Matatizo',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('ward', 'Kata'), ('district', 'Wilaya'), ('region', 'Mkoa'), ('zone', 'Kanda'), ('national', 'Taifa')], default='ward', max_length=12)),
                ('subject', models.CharField(blank=True, max_length=160, verbose_name='Kichwa')),
                ('last_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='members.member')),
            ],
            options={
                'verbose_name': 'Mazungumzo',
                'verbose_name_plural': 'Mazungumzo',
                'ordering': ['-last_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_leader', models.BooleanField(default=False)),
                ('body', models.TextField(verbose_name='Ujumbe')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='programs.thread')),
            ],
            options={
                'verbose_name': 'Ujumbe',
                'verbose_name_plural': 'Ujumbe',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status', 'level'], name='programs_ca_status_e0c4ae_idx'),
        ),
    ]
