# Generated by Django 5.0.6 on 2026-09-04 02:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_broadcast_case_caseevent_thread_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pair_key', models.CharField(db_index=True, max_length=40, unique=True)),
                ('last_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_a', to=settings.AUTH_USER_MODEL)),
                ('b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_b', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mazungumzo ya Viongozi',
                'verbose_name_plural': 'Mazungumzo ya Viongozi',
                'ordering': ['-last_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(verbose_name='Ujumbe')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='programs.chat')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ujumbe wa Kiongozi',
                'verbose_name_plural': 'Ujumbe wa Viongozi',
                'ordering': ['created_at'],
            },
        ),
    ]
