# Generated by Django 5.0.6 on 2026-08-02 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Mkoa')),
                ('code', models.CharField(blank=True, max_length=10)),
                ('map_x', models.FloatField(default=50, help_text='Nafasi kwenye ramani (0-100)')),
                ('map_y', models.FloatField(default=50)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Mkoa',
                'verbose_name_plural': 'Mikoa',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Wilaya')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='geo.region')),
            ],
            options={
                'verbose_name': 'Wilaya',
                'verbose_name_plural': 'Wilaya',
                'ordering': ['name'],
                'unique_together': {('region', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Tawi')),
                ('address', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=24)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact_person', models.CharField(blank=True, max_length=120)),
                ('is_head_office', models.BooleanField(default=False)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches', to='geo.district')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='geo.region')),
            ],
            options={
                'verbose_name': 'Tawi',
                'verbose_name_plural': 'Matawi',
                'ordering': ['-is_head_office', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Kata')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='geo.district')),
            ],
            options={
                'verbose_name': 'Kata',
                'verbose_name_plural': 'Kata',
                'ordering': ['name'],
            },
        ),
    ]
