# Generated by Django 5.0.6 on 2026-08-03 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='kind',
            field=models.CharField(choices=[('DC', 'Wilaya'), ('MC', 'Manispaa'), ('CC', 'Jiji'), ('TC', 'Mji')], default='DC', max_length=2, verbose_name='Aina'),
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Kanda')),
                ('name_en', models.CharField(blank=True, max_length=80)),
                ('code', models.SlugField(max_length=20, unique=True)),
                ('office', models.CharField(blank=True, max_length=120, verbose_name='Ofisi ya Kanda')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zones', to=settings.AUTH_USER_MODEL, verbose_name='Mratibu')),
            ],
            options={
                'verbose_name': 'Kanda',
                'verbose_name_plural': 'Kanda',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='region',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regions', to='geo.zone', verbose_name='Kanda'),
        ),
    ]
