# Generated by Django 5.0.6 on 2026-08-03 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_district_kind_zone_region_zone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['name', 'kind'], 'verbose_name': 'Halmashauri', 'verbose_name_plural': 'Halmashauri'},
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('region', 'name', 'kind')},
        ),
    ]
