# Generated by Django 5.0.6 on 2026-09-02 22:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_alter_district_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('ward', 'Kata'), ('district', 'Wilaya'), ('region', 'Mkoa'), ('zone', 'Kanda'), ('national', 'Taifa')], max_length=12, verbose_name='Ngazi')),
                ('post', models.CharField(choices=[('chair', 'Mwenyekiti'), ('secretary', 'Katibu'), ('treasurer', 'Mweka Hazina')], default='chair', max_length=12, verbose_name='Wadhifa')),
                ('started_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='Ameanza')),
                ('ended_on', models.DateField(blank=True, null=True, verbose_name='Amemaliza')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Maelezo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaders', to='geo.district', verbose_name='Wilaya')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaders', to='geo.region', verbose_name='Mkoa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderships', to=settings.AUTH_USER_MODEL, verbose_name='Mtumiaji')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaders', to='geo.ward', verbose_name='Kata')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaders', to='geo.zone', verbose_name='Kanda')),
            ],
            options={
                'verbose_name': 'Kiongozi',
                'verbose_name_plural': 'Viongozi',
                'ordering': ['level', 'post'],
                'indexes': [models.Index(fields=['level', 'ended_on'], name='geo_leaders_level_e43bff_idx')],
            },
        ),
    ]
