# Generated by Django 5.0.6 on 2026-09-30 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0004_leadership"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadership",
            name="post",
            field=models.CharField(
                choices=[
                    ("chair", "Mwenyekiti"),
                    ("vice_chair", "Makamu Mwenyekiti"),
                    ("secretary", "Katibu"),
                    ("asst_sec", "Katibu Msaidizi"),
                    ("treasurer", "Mweka Hazina"),
                    ("asst_treas", "Mweka Hazina Msaidizi"),
                    ("committee", "Mjumbe"),
                ],
                default="chair",
                max_length=12,
                verbose_name="Wadhifa",
            ),
        ),
    ]
