# Generated by Django 5.0.6 on 2026-08-09 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='milestone',
            options={'ordering': ['order', 'year'], 'verbose_name': 'Hatua ya Historia', 'verbose_name_plural': 'Historia ya MUWESTA'},
        ),
    ]
