# Generated by Django 5.0.6 on 2026-08-09 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def approve_existing(apps, schema_editor):
    """Matangazo yaliyokuwepo yalikuwa hadharani — yasipotee."""
    apps.get_model('content', 'Announcement').objects.update(status='approved')


def undo(apps, schema_editor):
    pass



class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_milestone_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-is_urgent', '-published_on', '-id'], 'verbose_name': 'Tangazo', 'verbose_name_plural': 'Matangazo'},
        ),
        migrations.AddField(
            model_name='announcement',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Muda wa idhini'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements_approved', to=settings.AUTH_USER_MODEL, verbose_name='Ameidhinisha'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements_created', to=settings.AUTH_USER_MODEL, verbose_name='Ameandaa'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_urgent',
            field=models.BooleanField(default=False, help_text="Linang'aa juu ya ukurasa wa mwanzo.", verbose_name='Ni la dharura'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='review_note',
            field=models.CharField(blank=True, max_length=200, verbose_name='Sababu'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='status',
            field=models.CharField(choices=[('draft', 'Rasimu'), ('pending', 'Inasubiri idhini'), ('approved', 'Imeidhinishwa'), ('rejected', 'Imekataliwa')], default='draft', max_length=12, verbose_name='Hali'),
        ),
        migrations.RunPython(approve_existing, undo),
    ]
