# Generated by Django 5.0.6 on 2026-08-19 22:48

from django.db import migrations, models

ZAMANI = ("Nkuhungu, Dodoma, Tanzania", "Nkuhungu, Dodoma", "")
MPYA = "Shariff PBZ House, Nyerere Square, Dodoma"


def sasisha(apps, schema_editor):
    """
    Kubadilisha `default` hakusaidii rekodi iliyokwisha hifadhiwa.
    `SiteSetting` huundwa mara moja tu, kwa hiyo tovuti iliyoko hewani
    ingebaki na anwani ya zamani milele. Hii inaisasisha.

    Inagusa tu rekodi zenye anwani ya zamani hasa — mtu akiwa ameiandika
    yake mwenyewe kupitia paneli ya usimamizi, haiguswi.
    """
    SiteSetting = apps.get_model("content", "SiteSetting")
    for s in SiteSetting.objects.all():
        fields = []
        if s.address in ZAMANI:
            s.address = MPYA
            fields.append("address")
        if s.address_en in ZAMANI:
            s.address_en = MPYA
            fields.append("address_en")
        if fields:
            s.save(update_fields=fields)


def rudisha(apps, schema_editor):
    SiteSetting = apps.get_model("content", "SiteSetting")
    SiteSetting.objects.filter(address=MPYA).update(
        address=ZAMANI[0], address_en=ZAMANI[0])


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_muwesta_leaders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='address',
            field=models.CharField(default=MPYA, max_length=200),
        ),
        migrations.RunPython(sasisha, rudisha),
    ]
