# Generated by Django 5.0.6 on 2026-08-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_sitesetting_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='key',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
    ]
