# Generated by Django 5.0.6 on 2026-08-24 01:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_notification_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='Namba')),
                ('text', models.TextField(verbose_name='Ujumbe')),
                ('reference', models.CharField(blank=True, max_length=60)),
                ('status', models.CharField(choices=[('queued', 'Kwenye foleni'), ('sent', 'Imetumwa'), ('failed', 'Imekata tamaa')], db_index=True, default='queued', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=200)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'SMS ya Foleni',
                'verbose_name_plural': 'SMS za Foleni',
                'ordering': ['created_at'],
            },
        ),
    ]
