# Generated by Django 5.0.6 on 2026-09-24 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_smsoutbox"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="legal_effective_on",
            field=models.DateField(
                blank=True, null=True, verbose_name="Nyaraka zinaanza kutumika"
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="map_url",
            field=models.URLField(blank=True, verbose_name="Kiungo cha Ramani"),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="meta_description",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Maelezo mafupi"
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="meta_description_en",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="org_short",
            field=models.CharField(
                default="MUWESTA", max_length=24, verbose_name="Kifupi"
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="phone_support",
            field=models.CharField(
                blank=True, max_length=24, verbose_name="Simu ya Msaada"
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="po_box",
            field=models.CharField(blank=True, max_length=60, verbose_name="S.L.P."),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="values_line",
            field=models.CharField(
                default="Imani, Huruma, Huduma, Maendeleo",
                max_length=160,
                verbose_name="Maadili",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="values_line_en",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="website",
            field=models.URLField(blank=True, verbose_name="Tovuti"),
        ),
        migrations.AddField(
            model_name="verse",
            name="scene",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="verse",
            name="slot",
            field=models.CharField(
                choices=[
                    ("home", "Ukurasa wa mbele"),
                    ("kuhusu", "Kuhusu Sisi"),
                    ("mawasiliano", "Mawasiliano"),
                    ("uanachama", "Uanachama"),
                    ("dashibodi", "Dashibodi"),
                ],
                default="dashibodi",
                max_length=20,
                verbose_name="Inaonekana wapi",
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="org_name",
            field=models.CharField(
                default="Muslim Welfare Society of Tanzania",
                max_length=140,
                verbose_name="Jina la Shirika",
            ),
        ),
    ]
