# Generated by Django 5.0.6 on 2026-09-24 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0008_sitesetting_legal_effective_on_sitesetting_map_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("phone", "Simu"), ("email", "Barua Pepe")],
                        default="phone",
                        max_length=10,
                        verbose_name="Aina",
                    ),
                ),
                ("label", models.CharField(max_length=80, verbose_name="Idara")),
                ("label_en", models.CharField(blank=True, max_length=80)),
                (
                    "value",
                    models.CharField(
                        max_length=120, verbose_name="Namba au Barua Pepe"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Inatumika"),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Namba ya Mawasiliano",
                "verbose_name_plural": "Namba za Mawasiliano",
                "ordering": ["kind", "order"],
            },
        ),
    ]
