# Generated by Django 5.0.6 on 2026-08-02 09:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Jina')),
                ('name_en', models.CharField(blank=True, max_length=40)),
                ('code', models.CharField(help_text='B, S, G, P, F — inatumika kwenye namba ya uanachama', max_length=1, unique=True, verbose_name='Herufi')),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ada ya mwezi')),
                ('points_per_payment', models.PositiveIntegerField(default=10, verbose_name='Pointi kwa malipo')),
                ('colour', models.CharField(default='#12864a', max_length=20)),
                ('benefits', models.TextField(blank=True, help_text='Mstari mmoja kwa kila faida', verbose_name='Faida')),
                ('benefits_en', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False, verbose_name='Maarufu')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Kategoria ya Uanachama',
                'verbose_name_plural': 'Kategoria za Uanachama',
                'ordering': ['order', 'monthly_fee'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership_no', models.CharField(blank=True, max_length=32, unique=True, verbose_name='Namba ya Mwanachama')),
                ('account_no', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Namba ya Akaunti')),
                ('full_name', models.CharField(max_length=140, verbose_name='Jina Kamili')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Mwanaume'), ('female', 'Mwanamke')], max_length=10, verbose_name='Jinsia')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Tarehe ya Kuzaliwa')),
                ('national_id', models.CharField(blank=True, max_length=32, verbose_name='Namba ya Kitambulisho')),
                ('nationality', models.CharField(blank=True, default='Mtanzania', max_length=60, verbose_name='Uraia')),
                ('religion', models.CharField(blank=True, default='Kiislamu', max_length=40, verbose_name='Dini')),
                ('occupation', models.CharField(blank=True, max_length=100, verbose_name='Kazi')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/')),
                ('phone', models.CharField(max_length=24, verbose_name='Simu')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Barua Pepe')),
                ('street', models.CharField(blank=True, max_length=120, verbose_name='Mtaa / Kijiji')),
                ('address', models.TextField(blank=True, verbose_name='Anuani Kamili')),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Imesitishwa'), ('expired', 'Imeisha muda')], default='active', max_length=12, verbose_name='Hali')),
                ('joined_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='Tarehe ya Usajili')),
                ('expires_on', models.DateField(blank=True, null=True, verbose_name='Tarehe ya Kuisha')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='geo.branch')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='members.category')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='geo.district')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='geo.region')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member', to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='geo.ward')),
            ],
            options={
                'verbose_name': 'Mwanachama',
                'verbose_name_plural': 'Wanachama',
                'ordering': ['-joined_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=140, verbose_name='Jina')),
                ('relationship', models.CharField(max_length=60, verbose_name='Uhusiano')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('phone', models.CharField(blank=True, max_length=24)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family', to='members.member')),
            ],
            options={
                'verbose_name': 'Mwanafamilia',
                'verbose_name_plural': 'Familia',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serial', models.CharField(blank=True, max_length=40, unique=True)),
                ('issued_on', models.DateField(default=django.utils.timezone.localdate)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('printed', models.BooleanField(default=False, verbose_name='Imechapishwa')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='members.member')),
            ],
            options={
                'verbose_name': 'Kadi ya Uanachama',
                'verbose_name_plural': 'Kadi za Uanachama',
                'ordering': ['-issued_on'],
            },
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=140, verbose_name='Jina')),
                ('relationship', models.CharField(max_length=60, verbose_name='Uhusiano')),
                ('phone', models.CharField(blank=True, max_length=24)),
                ('percentage_share', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Asilimia')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='members.member')),
            ],
            options={
                'verbose_name': 'Mnufaika',
                'verbose_name_plural': 'Wanufaika',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=32, unique=True, verbose_name='Namba ya Maombi')),
                ('full_name', models.CharField(max_length=140, verbose_name='Jina Kamili')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Mwanaume'), ('female', 'Mwanamke')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('national_id', models.CharField(blank=True, max_length=32)),
                ('nationality', models.CharField(blank=True, default='Mtanzania', max_length=60)),
                ('religion', models.CharField(blank=True, default='Kiislamu', max_length=40)),
                ('phone', models.CharField(max_length=24, verbose_name='Simu')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('street', models.CharField(blank=True, max_length=120)),
                ('address', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='applications/')),
                ('status', models.CharField(choices=[('pending', 'Inasubiri'), ('review', 'Kwenye Usahihishaji'), ('approved', 'Imepitishwa'), ('rejected', 'Imekataliwa')], default='pending', max_length=12)),
                ('note', models.TextField(blank=True, verbose_name='Maelezo')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.district')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.region')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.ward')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='members.category')),
                ('member', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='members.member')),
            ],
            options={
                'verbose_name': 'Ombi la Uanachama',
                'verbose_name_plural': 'Maombi ya Uanachama',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['status'], name='members_mem_status_734de0_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['category'], name='members_mem_categor_4e1e81_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['region'], name='members_mem_region__e3716b_idx'),
        ),
    ]
