# Generated by Django 5.0.6 on 2026-08-03 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_selectable',
            field=models.BooleanField(default=True, help_text='Ikizimwa, mwombaji hawezi kuichagua mwenyewe. Msimamizi pekee ndiye anayeweza kumpandisha mwanachama kwenye daraja hili.', verbose_name='Inaweza kuchaguliwa'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_special',
            field=models.BooleanField(default=False, help_text='Linaonyeshwa kwa heshima kwenye tovuti lakini si la kuomba.', verbose_name='Daraja maalum'),
        ),
    ]
