# Generated by Django 5.0.6 on 2026-08-03 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_alter_district_options_and_more'),
        ('members', '0002_category_is_selectable_category_is_special'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='address',
            field=models.TextField(blank=True, verbose_name='Anuani ya Posta'),
        ),
        migrations.AlterField(
            model_name='application',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='members.category', verbose_name='Aina ya Uanachama'),
        ),
        migrations.AlterField(
            model_name='application',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Tarehe ya Kuzaliwa'),
        ),
        migrations.AlterField(
            model_name='application',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.district', verbose_name='Halmashauri'),
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Barua Pepe'),
        ),
        migrations.AlterField(
            model_name='application',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Mwanaume'), ('female', 'Mwanamke')], max_length=10, verbose_name='Jinsia'),
        ),
        migrations.AlterField(
            model_name='application',
            name='national_id',
            field=models.CharField(blank=True, max_length=32, verbose_name='Namba ya Kitambulisho (NIDA)'),
        ),
        migrations.AlterField(
            model_name='application',
            name='nationality',
            field=models.CharField(blank=True, default='Mtanzania', max_length=60, verbose_name='Uraia'),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.CharField(max_length=24, verbose_name='Namba ya Simu'),
        ),
        migrations.AlterField(
            model_name='application',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='applications/', verbose_name='Picha ya Pasipoti'),
        ),
        migrations.AlterField(
            model_name='application',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.region', verbose_name='Mkoa'),
        ),
        migrations.AlterField(
            model_name='application',
            name='religion',
            field=models.CharField(blank=True, default='Kiislamu', max_length=40, verbose_name='Dini'),
        ),
        migrations.AlterField(
            model_name='application',
            name='street',
            field=models.CharField(blank=True, max_length=120, verbose_name='Mtaa / Kijiji'),
        ),
        migrations.AlterField(
            model_name='application',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.ward', verbose_name='Kata'),
        ),
    ]
