# Generated by Django 5.0.6 on 2026-08-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_application_address_alter_application_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='annual_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Hulipwa kila mwaka.', max_digits=12, verbose_name='Ada ya mwaka'),
        ),
        migrations.AddField(
            model_name='category',
            name='duration_years',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Muda wa uanachama (miaka)'),
        ),
        migrations.AddField(
            model_name='category',
            name='has_card',
            field=models.BooleanField(default=True, verbose_name='Kadi ya uanachama'),
        ),
        migrations.AddField(
            model_name='category',
            name='has_certificate',
            field=models.BooleanField(default=True, verbose_name='Cheti cha shukrani'),
        ),
        migrations.AddField(
            model_name='category',
            name='has_events',
            field=models.BooleanField(default=True, verbose_name='Matukio na mafunzo'),
        ),
        migrations.AddField(
            model_name='category',
            name='has_leadership',
            field=models.BooleanField(default=False, verbose_name='Fursa za uongozi'),
        ),
        migrations.AddField(
            model_name='category',
            name='has_priority',
            field=models.BooleanField(default=False, verbose_name='Huduma za kipaumbele'),
        ),
        migrations.AddField(
            model_name='category',
            name='has_reports',
            field=models.BooleanField(default=True, verbose_name='Ripoti na taarifa'),
        ),
        migrations.AddField(
            model_name='category',
            name='points_plus',
            field=models.BooleanField(default=False, help_text='Ikiwashwa, alama zitaonyeshwa kama "2,000+".', verbose_name='Alama ni za chini kabisa'),
        ),
        migrations.AddField(
            model_name='category',
            name='recognition_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Alama za utambuzi'),
        ),
        migrations.AddField(
            model_name='category',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Hulipwa mara moja tu wakati wa kujiunga.', max_digits=12, verbose_name='Ada ya usajili'),
        ),
    ]
