# Generated by Django 5.0.6 on 2026-08-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_new_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='id_type',
            field=models.CharField(blank=True, choices=[('nida', 'NIDA'), ('driving', 'Leseni ya Udereva'), ('voter', 'Kadi ya Mpiga Kura'), ('passport', 'Pasipoti'), ('employee', 'Kitambulisho cha Kazi'), ('membership', 'Kitambulisho Kingine cha Uanachama')], default='nida', max_length=16, verbose_name='Aina ya Kitambulisho'),
        ),
        migrations.AddField(
            model_name='member',
            name='id_type',
            field=models.CharField(blank=True, choices=[('nida', 'NIDA'), ('driving', 'Leseni ya Udereva'), ('voter', 'Kadi ya Mpiga Kura'), ('passport', 'Pasipoti'), ('employee', 'Kitambulisho cha Kazi'), ('membership', 'Kitambulisho Kingine cha Uanachama')], default='nida', max_length=16, verbose_name='Aina ya Kitambulisho'),
        ),
        migrations.AlterField(
            model_name='application',
            name='national_id',
            field=models.CharField(blank=True, max_length=32, verbose_name='Namba ya Kitambulisho'),
        ),
    ]
