# Generated by Django 5.0.6 on 2026-08-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_platinum_to_diamond'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Inasubiri'), ('review', 'Kwenye Usahihishaji'), ('awaiting_payment', 'Inasubiri Malipo'), ('approved', 'Imepitishwa'), ('rejected', 'Imekataliwa')], default='pending', max_length=20),
        ),
    ]
