# Generated by Django 5.0.6 on 2026-08-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='duration_years',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Muda wa uanachama (miaka)'),
        ),
    ]
