# Generated by Django 5.0.6 on 2026-08-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_three_year_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='phone_verified',
            field=models.BooleanField(default=False, verbose_name='Namba Imethibitishwa'),
        ),
    ]
