# Generated by Django 5.0.6 on 2026-09-04 12:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_leadership'),
        ('members', '0012_application_phone_verified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['status', 'expires_on'], name='members_mem_status_963ff1_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['ward'], name='members_mem_ward_id_67b19c_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['district'], name='members_mem_distric_aa6faf_idx'),
        ),
    ]
